# Generated by Django 3.2.5 on 2021-07-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=30)),
                ('qNum', models.IntegerField()),
                ('mainQ', models.TextField()),
                ('subQuestion1', models.CharField(blank=True, max_length=2000)),
                ('subQuestion2', models.CharField(blank=True, max_length=2000)),
                ('subQuestion3', models.CharField(blank=True, max_length=2000)),
                ('ans1', models.CharField(blank=True, max_length=2000)),
                ('ans2', models.CharField(blank=True, max_length=2000)),
                ('ans3', models.CharField(blank=True, max_length=2000)),
                ('ans4', models.CharField(blank=True, max_length=2000)),
                ('selected_answer', models.CharField(blank=True, max_length=2000)),
            ],
        ),
    ]
