# Generated by Django 3.2.5 on 2021-07-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test_app', '0002_questionanswermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswermodel',
            name='subQuestion4',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
