# Generated by Django 3.2.5 on 2021-07-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test_app', '0003_questionanswermodel_subquestion4'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=6)),
            ],
        ),
    ]
